[package]
name = "appimage-runtime"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
backhand = "0.18.0"
elf = "0.7.4"
fork = "0.2.0"

[dev-dependencies]
runfiles = "0.1.0"
