[package]
name = "appimage-mount"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
memfd-exec = "0.2.1"
nix = { version = "0.29.0", features = ["fs", "process"] }
selecting = "1.2.0"
tempfile = "3.10.1"

[dev-dependencies]
runfiles = "0.1.0"
backhand = "0.18.0"
